version: "3.8"

services:
  app:
    image: my-node-app:latest
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - /app/node_modules  
    deploy:
      replicas: 2 
      resources:
        limits:
          cpus: "0.5"    
          memory: "512M" 
        reservations:
          cpus: "0.25"    
          memory: "256M"
      restart_policy:
        condition: on-failure
    networks:
      - app-network

networks:
  app-network:
    driver: overlay
 
