version: '3'
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    hostname: 'gitlab.local'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://john2110.ddns.net:8003'
        nginx['listen_port'] = 8003
        nginx['listen_https'] = false
        gitlab_rails['gitlab_shell_ssh_port'] = 8004
    ports:
      - '8003:8003'   # publish cổng HTTP trực tiếp
      - '8004:22'     # SSH cho git clone qua SSH
    volumes:
      - /home/gitlab/config:/etc/gitlab
      - /home/gitlab/logs:/var/log/gitlab
      - /home/gitlab/data:/var/opt/gitlab